#!/usr/bin/env node
/**
 * build.js — Cross-platform build script for Warp
 * Automatically locates and sources vcvars64.bat on Windows before running tauri build.
 * Run with: node scripts/build.js
 *
 * NOTE: This is an ES module (package.json has "type": "module").
 */

import { spawnSync } from "node:child_process";
import path from "node:path";
import fs from "node:fs";
import os from "node:os";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const isWindows = process.platform === "win32";

// ── Updater signing key ───────────────────────────────────────────────────────
// The updater needs signed artifacts (createUpdaterArtifacts in tauri.conf.json).
// Use the key generated by `npm run tauri signer generate -w ~/.tauri/warp.key`.
// In CI the same key arrives via the TAURI_SIGNING_PRIVATE_KEY secret.
const keyPath = path.join(os.homedir(), ".tauri", "warp.key");
if (!process.env.TAURI_SIGNING_PRIVATE_KEY && fs.existsSync(keyPath)) {
  process.env.TAURI_SIGNING_PRIVATE_KEY = keyPath;
}
if (!process.env.TAURI_SIGNING_PRIVATE_KEY_PASSWORD) {
  // The generated key has no password — set explicitly to "" so the signer
  // doesn't wait for an interactive prompt mid-build.
  process.env.TAURI_SIGNING_PRIVATE_KEY_PASSWORD = "";
}
if (!process.env.TAURI_SIGNING_PRIVATE_KEY) {
  const conf = JSON.parse(fs.readFileSync(path.join(ROOT, "src-tauri/tauri.conf.json"), "utf8"));
  if (conf?.bundle?.createUpdaterArtifacts) {
    const msg =
      `\nWARNING: createUpdaterArtifacts is enabled but no signing key was found.\n` +
      `  Expected: ${keyPath} (or TAURI_SIGNING_PRIVATE_KEY env var)\n` +
      `  The build will succeed but produce NO .sig files, so in-app updates won't work.\n` +
      `  Generate one with: npm run tauri signer generate -w ~/.tauri/warp.key --ci\n` +
      `  Then set TAURI_SIGNING_PRIVATE_KEY and TAURI_SIGNING_PRIVATE_KEY_PASSWORD (empty) as GitHub secrets.\n` +
      `  See README.md "In-app updates" + https://v2.tauri.app/plugin/updater/\n`;
    if (process.env.CI) {
      console.error(msg);
      console.error("Failing CI build because updater artifacts would be unsigned.");
      process.exit(1);
    } else {
      console.warn(msg);
    }
  }
}

if (!isWindows) {
  // macOS / Linux — just run tauri build directly
  const result = spawnSync("npm", ["run", "tauri", "--", "build"], {
    stdio: "inherit",
    shell: true,
  });
  if (result.status === 0) {
    // Best-effort: generate latest.json if signing artifacts exist
    const updater = spawnSync("node", ["scripts/updater-manifest.js"], {
      stdio: "inherit",
      shell: true,
    });
    if (updater.status !== 0) {
      console.warn("Updater manifest not generated — missing .sig? (see above)");
    }
  }
  process.exit(result.status ?? 1);
}

// ── Windows: find vcvars64.bat ────────────────────────────────────────────────
const vcSearchPaths = [
  "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat",
  "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat",
  "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\Professional\\VC\\Auxiliary\\Build\\vcvars64.bat",
  "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat",
  "C:\\Program Files\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Auxiliary\\Build\\vcvars64.bat",
  "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat",
];

const vcvars = vcSearchPaths.find((p) => fs.existsSync(p));

if (!vcvars) {
  console.error("\nERROR: Could not find vcvars64.bat");
  console.error("Install Visual Studio 2022 Build Tools with the C++ workload:");
  console.error(
    '  winget install Microsoft.VisualStudio.2022.BuildTools --override "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"',
  );
  process.exit(1);
}

console.log(`Found MSVC: ${vcvars}`);

// Write a temp batch file that sources vcvars then calls tauri build
const batContent = `@echo off\r\ncall "${vcvars}"\r\nnpm run tauri -- build\r\n`;
const batPath = path.join(__dirname, "_build_tmp.bat");
fs.writeFileSync(batPath, batContent);

const result = spawnSync("cmd", ["/c", batPath], {
  stdio: "inherit",
  cwd: path.join(__dirname, ".."),
});

// Cleanup
try {
  fs.unlinkSync(batPath);
} catch {}

if (result.status === 0) {
  const updater = spawnSync("node", ["scripts/updater-manifest.js"], {
    stdio: "inherit",
    cwd: path.join(__dirname, ".."),
    shell: true,
  });
  if (updater.status !== 0) {
    console.warn("Updater manifest not generated — missing .sig? (see above)");
  }
}

process.exit(result.status ?? 1);
